name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Package
        run: mvn clean package

      - name: Store Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-war
          path: target/*.war
